jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "webapp/Component-preload",
	"modules": {
		"webapp/Component.js": "sap.ui.define([\"sap/ui/core/UIComponent\",\"sap/ui/Device\",\"sap/ui/demo/basicTemplate/model/models\"],function(e,i,t){\"use strict\";return e.extend(\"sap.ui.demo.basicTemplate.Component\",{metadata:{manifest:\"json\"},init:function(){e.prototype.init.apply(this,arguments),this.setModel(t.createDeviceModel(),\"device\"),this.getRouter().initialize()}})});",
		"webapp/controller/App.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\"],function(e){\"use strict\";return e.extend(\"sap.ui.demo.basicTemplate.controller.App\",{onInit:function(){}})});",
		"webapp/controller/Detail.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\"],function(t){\"use strict\";return t.extend(\"sap.ui.demo.basicTemplate.controller.Detail\",{onInit:function(){this._oRouter=this.getOwnerComponent().getRouter(),this._oRouter.getRoute(\"detail\").attachPatternMatched(this._onPatternMatched,this)},onNavBackPress:function(){this._oRouter.navTo(\"master\")},_onPatternMatched:function(t){var e=t.getParameter(\"arguments\"),i=this.getView().getModel().getProperty(\"/list\");if(void 0!=i){var n=i.findIndex(t=>t.id==e.CityId);this.getView().bindElement(\"/list/\"+n)}}})});",
		"webapp/controller/Master.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"sap/ui/model/json/JSONModel\"],function(e,t){\"use strict\";return e.extend(\"sap.ui.demo.basicTemplate.controller.Master\",{onInit:function(){},onItemPress:function(e){var t=e.getSource().getBindingContext().getObject().id;this.getOwnerComponent().getRouter().navTo(\"detail\",{CityId:t})}})});",
		"webapp/model/formatter.js": "sap.ui.define([],function(){\"use strict\";return{}});",
		"webapp/model/models.js": "sap.ui.define([\"sap/ui/model/json/JSONModel\",\"sap/ui/Device\"],function(e,n){\"use strict\";return{createDeviceModel:function(){var i=new e(n);return i.setDefaultBindingMode(\"OneWay\"),i}}});",
		"webapp/test/integration/AllJourneys.js": "jQuery.sap.require(\"sap.ui.qunit.qunit-css\"),jQuery.sap.require(\"sap.ui.thirdparty.qunit\"),jQuery.sap.require(\"sap.ui.qunit.qunit-junit\"),QUnit.config.autostart=!1,sap.ui.require([\"sap/ui/test/Opa5\",\"sap/ui/demo/basicTemplate/test/integration/pages/Common\",\"sap/ui/test/opaQunit\",\"sap/ui/demo/basicTemplate/test/integration/pages/App\"],function(e,i){\"use strict\";e.extendConfig({arrangements:new i,viewNamespace:\"sap.ui.demo.basicTemplate.view.\"}),sap.ui.require([\"sap/ui/demo/basicTemplate/test/integration/navigationJourney\"],function(){QUnit.start()})});",
		"webapp/test/integration/navigationJourney.js": "sap.ui.define([\"sap/ui/test/opaQunit\"],function(e){\"use strict\";QUnit.module(\"Navigation Journey\"),e(\"Should see the initial page of the app\",function(e,i,p){e.iStartTheApp(),i.onTheAppPage.iLookAtTheScreen(),p.onTheAppPage.iShouldSeeTheApp().and.iTeardownMyAppFrame()})});",
		"webapp/test/integration/pages/App.js": "sap.ui.define([\"sap/ui/test/Opa5\",\"sap/ui/demo/basicTemplate/test/integration/pages/Common\"],function(e,s){\"use strict\";e.createPageObjects({onTheAppPage:{baseClass:s,actions:{},assertions:{iShouldSeeTheApp:function(){return this.waitFor({id:\"app\",viewName:\"App\",success:function(){e.assert.ok(!0,\"The App view is displayed\")},errorMessage:\"Did not find the App view\"})}}}})});",
		"webapp/test/integration/pages/Common.js": "sap.ui.define([\"sap/ui/test/Opa5\"],function(e){\"use strict\";return e.extend(\"sap.ui.demo.basicTemplate.test.integration.pages.Common\",{iStartTheApp:function(e){var t,i,a;e=e||{},this.iStartMyAppInAFrame((t=e.hash,a=jQuery.sap.getResourcePath(\"sap/ui/demo/basicTemplate/app\",\".html\"),t=t||\"\",a+(i=i?\"?\"+i:\"\")+(t=t?\"#\"+(0===t.indexOf(\"/\")?t.substring(1):t):\"\")))},iLookAtTheScreen:function(){return this}})});",
		"webapp/test/unit/allTests.js": "sap.ui.define([\"test/unit/model/formatter\",\"test/unit/controller/App.controller\"],function(){\"use strict\"});",
		"webapp/test/unit/controller/App.controller.js": "sap.ui.define([\"sap/ui/demo/basicTemplate/controller/App.controller\"],function(t){\"use strict\";QUnit.module(\"App Controller\"),QUnit.test(\"I should test the app controller\",function(e){var o=new t;o.onInit(),e.ok(o)})});",
		"webapp/test/unit/model/formatter.js": "sap.ui.define([\"sap/ui/demo/basicTemplate/model/formatter\"],function(){\"use strict\";QUnit.module(\"Formatters\"),QUnit.test(\"I should test my formatters\",function(t){t.ok(!0)})});",
		"webapp/view/App.view.xml": "<mvc:View\n\tcontrollerName=\"sap.ui.demo.basicTemplate.controller.App\"\n\txmlns:mvc=\"sap.ui.core.mvc\"\n\tdisplayBlock=\"true\"\n\txmlns=\"sap.m\"><SplitApp id=\"idApp\"></SplitApp></mvc:View>",
		"webapp/view/Detail.view.xml": "<mvc:View\n\tcontrollerName=\"sap.ui.demo.basicTemplate.controller.Detail\"\n\txmlns:mvc=\"sap.ui.core.mvc\"\n\tdisplayBlock=\"true\"\n\txmlns=\"sap.m\"><Page title=\"Aktuální počasí\" showNavButton=\"{device>/system/phone}\" navButtonPress=\"onNavBackPress\"><Text text=\"{id}\"/><ObjectHeader title=\"{name}\"\n\t\t\t\tnumber=\"{main/temp}\"\n\t\t\t\tnumberUnit=\"°C\"\n\t\t\t\ticon=\"{='http://openweathermap.org/img/w/'+${weather/0/icon}+'.png'}\"    \n       ><attributes><ObjectAttribute text=\"{='Tlak: ' + ${main/pressure}} hPa\" visible=\"{=!!${main/pressure}}\" /><ObjectAttribute text=\"{='Vlhkost: ' + ${main/humidity}}%\" visible=\"{=!!${main/humidity}}\" /></attributes></ObjectHeader></Page></mvc:View>",
		"webapp/view/Master.view.xml": "<mvc:View\n\tcontrollerName=\"sap.ui.demo.basicTemplate.controller.Master\"\n\txmlns:mvc=\"sap.ui.core.mvc\"\n\tdisplayBlock=\"true\"\n\txmlns=\"sap.m\"><Page><List\n\t\t\theaderText=\"Cities\"\n\t\t\tgrowing=\"true\"\n\t\t\titems=\"{/list}\"><ObjectListItem\n\t\t\t\ttype=\"Navigation\"\n\t\t\t\tpress=\"onItemPress\"\n\t\t\t\ttitle=\"{name}\"\n\t\t\t\tnumber=\"{main/temp}\"\n\t\t\t\tnumberUnit=\"°C\"\n\t\t\t\ticon=\"{='http://openweathermap.org/img/w/'+${weather/0/icon}+'.png'}\"\n\t\t\t\t></ObjectListItem></List></Page></mvc:View>",
		"webapp/i18n/i18n.properties": "title=OpenUI5 Basic Template\nappTitle=OpenUI5 Basic Template\nappDescription=Best-practice starting point for building a freestyle app"
	}
});